### ISSUE TITLE
Make IMDB column into url

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/plex2csv.bundle#107]
So when clicked on from a spreadsheet, it'll launch a browser

[https://forums.plex.tv/discussion/comment/1177800/#Comment_1177800](url)

**Comment by ukdtom** [comment]
And sadly, this will not work for at least Libra office :-1: 

But changed the field from just the tt number into the full url

**Comment by SvenErik1968** [comment]
I just did an export level 3 on my movie library using plex2csv v0.0.4.9.
And I noticed that the IMDB Id field contained an url to imdb formatet like this:

`http://www.imdb.com/title/edb://46510`

where the 46510 is themoviedb id. So looks like something is going wrong here...

**Comment by SvenErik1968** [comment]
Another thing; since themoviedb is the mayor metadatabase for movies in Plex today, would it not be useful to have a themoviedb id field? I did a check of my csv file, and out of the 4270 movies listed, only 10 had an imdb id while 4057 had an themoviedb id.

**Comment by ukdtom** [comment]
Heh.....not seen that :-(

Would it be possible for you to upload the XML info for a movie, that has themoviedb as the id?

Either here, or in a PM on Plex forums

**Comment by SvenErik1968** [comment]
Yes, here is the XML info for the movie I used as an example, **The 'High Sign'** from 1921.
[**IMDB**](http://www.imdb.com/title/tt0012278/) and [**themoviedb**](https://www.themoviedb.org/movie/46510).

`<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="Movies" librarySectionUUID="0e8c2917-c2e7-481e-90f1-8ff851673361" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1461326894">
<Video ratingKey="72058" key="/library/metadata/72058" guid="com.plexapp.agents.themoviedb://46510?lang=en" librarySectionID="2" studio="Joseph M. Schenck Productions" type="movie" title="The 'High Sign'" titleSort="'High Sign'" summary="Buster is thrown off a train near an amusement park. There he gets a job in a shooting gallery run by the Blinking Buzzards mob. Ordered to kill a businessman, he winds up protecting the man and his daughter by outfitting their home with trick devices." rating="5.7" year="1921" tagline="What A Predicament!" thumb="/library/metadata/72058/thumb/1464433252" art="/library/metadata/72058/art/1464433252" duration="1237000" originallyAvailableAt="1921-04-18" addedAt="1463395389" updatedAt="1464433252" chapterSource="">
<Media videoResolution="480" id="93004" duration="1237000" bitrate="1510" width="652" height="514" aspectRatio="1.33" audioChannels="2" audioCodec="aac" videoCodec="h264" container="mkv" videoFrameRate="PAL" audioProfile="lc" videoProfile="main">
<Part accessible="1" exists="1" id="93927" key="/library/parts/93927/file.mkv" duration="1237000" file="\\DISKSTATION2\Film\1920s\The High Sign (1921)\The High Sign (1921).mkv" size="233456902" audioProfile="lc" container="mkv" videoProfile="main">
<Stream id="216399" streamType="1" default="1" codec="h264" index="0" bitrate="1510" language="English" languageCode="eng" bitDepth="8" cabac="1" chromaSubsampling="4:2:0" codecID="V_MPEG4/ISO/AVC" colorRange="tv" colorSpace="smpte170m" frameRate="25.000" frameRateMode="vfr" hasScalingMatrix="0" height="514" level="40" pixelFormat="yuv420p" profile="main" refFrames="4" scanType="progressive" width="652"/>
<Stream id="216400" streamType="2" selected="1" default="1" codec="aac" index="1" channels="2" language="English" languageCode="eng" audioChannelLayout="stereo" codecID="A_AAC" duration="1237000" profile="lc" samplingRate="22050"/>
</Part>
</Media>
<Genre id="1709" tag="Crime" count="315"/>
<Genre id="1973" tag="Comedy" count="1731"/>
<Writer id="8734" tag="Edward F. Cline" count="14"/>
<Writer id="8733" tag="Buster Keaton" count="20"/>
<Director id="8732" tag="Edward F. Cline" count="16"/>
<Director id="8731" tag="Buster Keaton" count="30"/>
<Producer id="8738" tag="Joseph M. Schenck" count="19"/>
<Country id="1715" tag="USA" count="2576"/>
<Role id="8735" tag="Buster Keaton" count="38" role="Our Hero" thumb="http://image.tmdb.org/t/p/original/pYsC0NiYf4EtyVv637Ax5mB9RJz.jpg"/>
<Role id="23450" tag="Bartine Burkett" count="2" role="Miss Nickelnurser"/>
<Role id="23451" tag="Charles Dorety" count="3" role="Gang member"/>
<Role id="10596" tag="Joe Roberts" count="19" role="Leader of Buzzards" thumb="http://image.tmdb.org/t/p/original/yhEKWSxEyaa6SveFMwe3XMHBalt.jpg"/>
<Role id="14962" tag="Al St. John" count="8" role="Man on beach during target practice" thumb="http://image.tmdb.org/t/p/original/oQp3IrUKlI1qH6HVMlLbvpM0e2j.jpg"/>
<Role id="60754" tag="Ingram B. Pickett" role="Tiny Tim"/>
<Extras size="0"></Extras>
</Video>
</MediaContainer>`

**Comment by ukdtom** [comment]
Thanks.....Just what the doctor ordered.....I'll look into this, and thanks

/T

**Comment by ukdtom** [comment]
Asking here, since not a native english dude....

If I was to rename the column name from "IMDB ID" into something more generic, what would you suggest?

**Comment by SvenErik1968** [comment]
Since the ID can relate to many different metadatabases, how about **MetaDB ID**?

Then maybe add some logic to correctly format the URL based on the agent used.

I took a look at one of the few movies that has a IMDB ID (Freebase) (See XML below), and I see that one used the _com.plexapp.agents.imdb_ agent, while the ones with themoviedb ID uses _com.plexapp.agents.themoviedb_, and theTVdb uses _com.plexapp.agents.thetvdb_

That should cover the most used metadatabases.

`<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="Movies" librarySectionUUID="0e8c2917-c2e7-481e-90f1-8ff851673361" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1461326894">
<Video ratingKey="43702" key="/library/metadata/43702" guid="com.plexapp.agents.imdb://tt0780011?lang=en" librarySectionID="2" studio="distributors = -->" type="movie" title="Extreme Game" originalTitle="เด็กระเบิดยืดแล้วยึด" summary="In a paint ball game, a victory means the greatst acceptation, which the winner will be gotten from his friends. So, a pain in the ass of young gangster tries to defeat his rivals in a building. He finds that this place is a shelter of criminals while the game is running. How does he survivie from a dangerous surrounding?" rating="5.5" year="1996" thumb="/library/metadata/43702/thumb/1455552234" art="/library/metadata/43702/art/1455552234" duration="6317458" originallyAvailableAt="1996-04-05" addedAt="1450644938" updatedAt="1455552234" chapterSource="">
<Media videoResolution="720" id="51981" duration="6317458" bitrate="2764" width="1280" height="720" aspectRatio="1.78" audioChannels="6" audioCodec="ac3" videoCodec="h264" container="mkv" videoFrameRate="24p" videoProfile="high">
<Part accessible="1" exists="1" id="52021" key="/library/parts/52021/file.mkv" duration="6317458" file="\\DISKSTATION2\Film\1990s\Dek raboet yeut laew yeut (1996)\Dek raboet yeut laew yeut (1996).mkv" size="2182839631" container="mkv" videoProfile="high">
<Stream id="132882" streamType="1" default="1" codec="h264" index="1" bitrate="2261" language="ไทย" languageCode="tha" bitDepth="8" cabac="1" chromaSubsampling="4:2:0" codecID="V_MPEG4/ISO/AVC" colorRange="tv" colorSpace="bt709" duration="6317458" frameRate="24.000" frameRateMode="cfr" hasScalingMatrix="0" height="720" level="31" pixelFormat="yuv420p" profile="high" refFrames="3" scanType="progressive" width="1280"/>
<Stream id="132881" streamType="2" selected="1" default="1" codec="ac3" index="0" channels="6" bitrate="448" language="ไทย" languageCode="tha" audioChannelLayout="5.1(side)" bitDepth="16" bitrateMode="cbr" codecID="A_AC3" dialogNorm="-31" duration="6317439" samplingRate="48000"/>
</Part>
</Media>
<Genre id="1886" tag="Action" count="699"/>
<Director id="56267" tag="Khomsan Srisawat"/>
<Country id="1975" tag="Thailand" count="461"/>
<Role id="3227" tag="Suttida Kasemsan Na Ayutthaya" count="3" role=""/>
<Role id="56268" tag="Thanaphong Khlaaiphongphan" role=""/>
<Role id="55805" tag="Thana 'Oil' Suthikamorn" count="2" role=""/>
<Role id="56269" tag="Johnny Unwa" role=""/>
<Role id="56270" tag="Chanit Yaisamer" count="2" role=""/>
<Collection id="54839" tag="Thai Audio" count="478"/>
<Field name="title" locked="1"/>
<Field name="titleSort" locked="1"/>
<Field name="originalTitle" locked="1"/>
<Field name="summary" locked="1"/>
<Field name="originallyAvailableAt" locked="1"/>
<Field name="collection" locked="1"/>
<Extras size="0"></Extras>
</Video>
</MediaContainer>`

**Comment by ukdtom** [comment]
Column name had a lot of suggestions, from different sources, but went by "MetaDb Link" :-)

Care to test https://github.com/ukdtom/plex2csv.bundle/archive/tommy-work.zip and then report back?

**Comment by ukdtom** [comment]
Ohh....and forgot....For TV-Shows, level 4 is needed ;-)

/T

**Comment by SvenErik1968** [comment]
Will test this afternoon after I get back from work :)

**Comment by SvenErik1968** [comment]
The movie export went ok, but the TV export crashed. I have sent you a msg on the Plex forum with link to the logs.

**Comment by ukdtom** [comment]
I see two issues in the logs :-(

First, I see a lot of exceptions in some medias, and one of them been "3 Women"
Could you perhaps send me the XML for that?

Secondly, I see a database timeout for an unknown media, in the url:
http://<IP_OF_PMS>:32400/library/metadata/19159?includeExtras=1&checkFiles=1&&X-Plex-Token=<YOUR_TOKEN>

If I could get the XML for that as well, it would be nice, and to locate your token, look in the end of the url, when getting the url for "3 Women"

Thanks

**Comment by SvenErik1968** [comment]
The XML files are here: https://www.dropbox.com/s/ty9nv5lmf74xc59/xml.zip?dl=0

The unknown media you mentioned is "24 S00E01".

**Comment by ukdtom** [comment]
The exceptions for like "3 Women" is due to PMS producing invalid XML's.
(Look @ the role in the XML)

This has been reported to Plex.

The error with the TV-Show seems to be a timeout, so could it be, that your PMS simply was stressed?, aka.....Does it happen again in a second run?

/T

**Comment by SvenErik1968** [comment]
Ahh, yes, the quotation marks within the character name should have been escaped.

Hope it will be fixed by Plex. In the meantime, I have edited the character name in themoviedb from _Mildred "Millie" Lammoreaux_ to _Mildred 'Millie' Lammoreaux_.

Tried to run the TV again via Plex.tv but it crashed again. Will check out the logs when I get home from work.

**Comment by SvenErik1968** [comment]
Sent you the new logs on Plex forum. Both with this version, and then I rolled back to the previous one, but with same result.

**Comment by ukdtom** [comment]
Might be this, but still unsure here

https://github.com/ukdtom/plex2csv.bundle/issues/111

**Comment by SvenErik1968** [comment]
That sounds plausible, and I do have a fairly large library that might cause this (847 shows with currently 28814 episodes according to PlexPy).
I turned the Plex debug level to Verbose and did a new TV export that also failed. Have sent you the link to the logs in Plex forum again.

**Comment by ukdtom** [comment]
Just odd that it used to work for you.

I sadly suspect, that newer versions of PMS are handling stuff differently, and thus why this now is exposed.

**Comment by ukdtom** [comment]
Care to redownload from tommy-branch, and try again?

**Comment by SvenErik1968** [comment]
It managed to get out 2231 episodes compared to 2230 episodes this time before it crashed...
Sent you a new log in the Plex forum.

**Comment by ukdtom** [comment]
This is so strange, cuz when I do it, using your database, it simply works.
And everything in the logs indicates a timeout in the backend, aka PMS too busy.

So......

Try and redownload the tommy-work branch again, since I now have added a timeout parameter to every call towards PMS.

You can adjust the timeout in the const.py file if needed.

Also, I noticed that you had the flag: "Check if file exists" turned on.
Above cause the PMS to verify/check in the filesystem if the file is actually present or not, and as such, puts further pressure on the PMS/file system.
And lastly, you are using a Windows box for your PMS.
Please check, that you don't have some kind of AntiVira/http inspection tool running, that also covers the loopback address (127.0.0.1) as well as the filesystem when PMS checks for file existence.

And please report back regardless ;-)

**Comment by SvenErik1968** [comment]
PMS is running on a Windows Server 2008 R2 box. The media is on 2 different Synology NAS.
I have downloaded the new version and completely turned of the AV for now.
Running an export now, and looking good so far...
But not sure how to un-check the "Check if file exists", can't find any switches for that in the web settings interface.

**Comment by SvenErik1968** [comment]
I am afraid it crashed again after exporting 2232 episodes. Updated log available in the same url as last time.

**Comment by ukdtom** [comment]
There should be a checkbox named "Check if files actually exists" right below the setting of Playlist export level.

**Comment by SvenErik1968** [comment]
LOL! No wonder I did not see it, I was looking for that in the PMS config...
Unchecked that and did a new run, but it crashed after 2232 episodes.

Running again after changing the PMSTIMEOUT to 30.

847 shows and 28816 episodes takes some time... But it is looking good so far, 4336 episodes exported as of now, so it looks like a success changing the PMSTIMEOUT value. And this is not exactly pushing my server, the CPU usage is around 12-25% and available RAM is about 9 GB out of 16 GB.

Unrelated to this issue, I took a look at the misc.py file, and think you need some more changes to the URL creation since themoviedb also can be used for TV series. So if it is a themoviedb ID/agent and it is a TV show, the URL should be like _https://www.themoviedb.org/tv/$ID_ ([Example](https://www.themoviedb.org/tv/1399)).

You should probably also look into a few more metadatabases that are used a lot, like _AniDB.net Metadata Agent_ used by the anime fans, _Open Movie Database_, and possibly some of the ones for adult content like _Data18 Metadata Agent_ and _Data18-Content Metadata Agent_; these are all available through the WebTools Unsupported AppStore.

**Comment by SvenErik1968** [comment]
That worked! About 2 hour 30 minutes from start to finish... ;-)

**Comment by ukdtom** [comment]
Thanks.

I'll change the default to 30 min. then.

And regarding the addition of other Metadata agents, I'll adopt those changes, when ever people send me sample XML's.

Sadly haven't got time to install all kinda metadata agents, and create test libs for them one by one :-(

Even though they are in my WebTools ;-)

And on a QNAP x86 with PMS running on it, and with a copy of your database, it took me about 35 min. for a complete export of TV-Shows in level 4!

**Comment by SvenErik1968** [comment]
My homebuilt PMS server has an AMD FX-6300 CPU with 16GB RAM. Maybe it is time to do a clean install of PMS...

Regarding the other agents, I will do some tests and then send you the XML files. Will 1 sample from each agent be sufficient for you?

**Comment by ukdtom** [comment]
That'll work just fine, with a single XML for each case, but be warned here.....

If you raise a GHI for those, I'll hold you up for testing ;-)

And huge thanks btw for your patience during this, as well as your great advocating of  Plex2CSV on Reddit

**Comment by SvenErik1968** [comment]
Here is the ones I have been able to test and get to work.

And I don't mind testing if you implement these. I know I personally would have use for the themoviedb for TV series since I have a few Thai TV series listed there that is not on thetvdb.

[com.plexapp.agents.anidb.tv_example.xml.txt](https://github.com/ukdtom/plex2csv.bundle/files/299335/com.plexapp.agents.anidb.tv_example.xml.txt)
[com.plexapp.agents.data18.movie_example.xml.txt](https://github.com/ukdtom/plex2csv.bundle/files/299336/com.plexapp.agents.data18.movie_example.xml.txt)
[com.plexapp.agents.imdb_with_openmoviedb.movie.example.xml.txt](https://github.com/ukdtom/plex2csv.bundle/files/299337/com.plexapp.agents.imdb_with_openmoviedb.movie.example.xml.txt)
[com.plexapp.agents.themoviedb.tv_example.xml.txt](https://github.com/ukdtom/plex2csv.bundle/files/299338/com.plexapp.agents.themoviedb.tv_example.xml.txt)

**Comment by ukdtom** [comment]
You asked 4 it, so it's payback time ;-)

Download V0.0.4.11 from the tommy-work branch, and please report back

/T

**Comment by SvenErik1968** [comment]
LOL! I will test it out, but probably not before next weekend since I decided to do a clean install of Plex, and it will take some time to get my libraries fully up and indexed before I can do some testing.

Hopefully this will fix the issue with the TV export too. After uninstalling Plex, I tried to delete the remaining folders and files, but after 10 minutes, Windows Explorer was still counting files and folders to delete, so I ended up reformatting the disk... ;-)

Sven-Erik

**Comment by ukdtom** [comment]
NP, I'll be here ;-)

**Comment by ukdtom** [comment]
And next time, simply rename the Library to Library.old

That way, you have a retrete and also can delete on demand

**Comment by SvenErik1968** [comment]
OK, I have rebuilt my library, though I still have some manual editing to do... And a new export of my TV library at level 4 took 21 minutes... ;-)

I have tested the AniDB, Data18, Open Movie Database and theMoviedb for TV series, all at Level 666. And the output looks good!

[TheMovieDB_TV-Level 666-20160610-231503.csv.txt](https://github.com/ukdtom/plex2csv.bundle/files/309818/TheMovieDB_TV-Level.666-20160610-231503.csv.txt)
[Anime-Level 666-20160610-231447.csv.txt](https://github.com/ukdtom/plex2csv.bundle/files/309820/Anime-Level.666-20160610-231447.csv.txt)
[Data18-Level 666-20160610-231453.csv.txt](https://github.com/ukdtom/plex2csv.bundle/files/309821/Data18-Level.666-20160610-231453.csv.txt)
[OpenMovieDatabase-Level 666-20160610-234719.csv.txt](https://github.com/ukdtom/plex2csv.bundle/files/309819/OpenMovieDatabase-Level.666-20160610-234719.csv.txt)

**Comment by ukdtom** [comment]
That is so cool, that you now got a fast system :-)

And I bet that the PMS timeout was a local issue for you, and no longer needed :dancer: 

But regardless, Huston, we have a go for the next version.

Once more, thanks for all you done so far, and Happy Plexing

/T
