### ISSUE TITLE
Option to add a BOM (Byte Order Marker) to the exported file

### ISSUE THREAD

**Issue by SvenErik1968** [ukdtom/plex2csv.bundle#139]
Would it be possible to add the option to generate the CSV as a UTF8-BOM?

It would make it easier at least for Excel users since Excel believes the file is in ANSI when the UTF8 file is without a BOM, but if I open the file in a text editor and convert it to UTF8-BOM first before importing it into Excel, it gets recognized to be in Unicode format.

**Comment by ukdtom** [comment]
Even though I feel your pain here, BOM is not recommended by unicode.org, and who am I to argue with them ;-)
http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf

As such, I'll not go down that path

But when said, I'm working on native xlsx output as well, which works nicely on Linux, but sadly broken on windows due to Plex Framework :-(

But haven't given up on that part yet though, just takes a lot more time than expected

**Comment by SvenErik1968** [comment]
OK, I understand. I knew it was not recommended, that why I asked if it could be added as an option you had to manually turn on in the settings.
Wishing you luck with getting the xlsx output to work!
Have a nice weekend!
