### ISSUE TITLE
Feature Request: File name path

### ISSUE THREAD

**Issue by Chucky-22** [ukdtom/plex2csv.bundle#142]
The current movie export does not export the file name path. Is it possible to include into Level 1

**Comment by ukdtom** [comment]
It's in level 5 and called "Part File"
https://github.com/ukdtom/plex2csv.bundle/wiki/Movie-Export-Level

And it'll not be a Level one thing, since there's a reason for the different levels, and level 1 only req. one call towards PMS, where the others req. two or more, in order to extract the needed info

**Comment by Chucky-22** [comment]
Sorry my mistake of interpretation . I meant the actual file path including the file name.
"Part File" Column only goes down to folder level and not the actual file name.

**Comment by ukdtom** [comment]
What version are you on?

Cuz works fine here, and outputs like:

`/share/MD0_DATA/.qpkg/HD_Station/share/M
D0_DATA/Video/Nyt/movies/dec/MyMovie (2
016)/MyMovie.mkv`

**Comment by Chucky-22** [comment]
V0.0.4.19

**Comment by Chucky-22** [comment]
Just found what the issue was. When I opened the csv file with Microsoft Excel 2010 it automatically has Wrap text enabled and therefore it only shows part of the file path the rest is hidden once you disable it you can see the full path name including the file name are on the same line.

Thank you for your time
